#!/bin/bash -xeu

scenario=$1
scenario_path=$2

bosh -n -d $scenario deploy e2e/manifests/deployment.yml \
  -o ${scenario_path}/ops.yml \
  -v scenario=$scenario

rg_name=$(get_rg_name ${scenario})
vm_name=$(get_vm_name ${scenario})
nic_name="${vm_name}-0"

enable_accelerated_networking=$(az network nic show --name ${nic_name} --resource-group ${rg_name} | jq -r '.enableAcceleratedNetworking')

bosh -n -d $scenario delete-deployment

if [ "${enable_accelerated_networking}" == "false" ]
then
  exit 1
fi
