#!/bin/bash -xeu

source e2e/functions/utils.sh
scenario=$1
scenario_path=$2

bosh -n -d $scenario deploy e2e/manifests/deployment.yml \
  -o ${scenario_path}/ops.yml \
  -v scenario=$scenario

rg_name=$(get_rg_name ${scenario})
vm_name=$(get_vm_name ${scenario})
nic_name="${vm_name}-0"

asg_id=$(az network nic show --name ${nic_name} --resource-group ${rg_name} | jq -r '.ipConfigurations[0].applicationSecurityGroups[0].id')
IFS='/' read -r -a asg_resource_id <<< "$asg_id"
asg_name=${asg_resource_id[-1]}

bosh -n -d $scenario delete-deployment

if [ "${asg_name}" != "default-asg" ]
then
  echo "The application security group is not assigned to the nic"
  exit 1
fi
