---
- type: replace
  path: /networks/-
  value:
    name: disable-ephemeral-disk
    type: manual
    subnets:
    - range: 10.0.23.0/24
      gateway: 10.0.23.1
      azs: [z1, z2, z3]
      dns: [168.63.129.16, 8.8.8.8]
      reserved: [10.0.23.0/30]
      cloud_properties:
        security_group: ((default_security_group))
        virtual_network_name: ((vnet_name))
        subnet_name: subnet-23
- type: replace
  path: /vm_extensions/-
  value:
    name: disable-ephemeral-disk
    cloud_properties:
      ephemeral_disk:
        use_root_disk: True

