---
- type: replace
  path: /networks/-
  value:
    - name: multiple-nics-1
      type: manual
      subnets:
      - range: 10.0.28.0/24
        gateway: 10.0.28.1
        azs: [z1, z2, z3]
        dns: [168.63.129.16, 8.8.8.8]
        reserved: [10.0.28.0/30]
        cloud_properties:
          security_group: ((default_security_group))
          virtual_network_name: ((vnet_name))
          subnet_name: subnet-28
    - name: multiple-nics-2
      type: manual
      subnets:
      - range: 10.0.29.0/24
        gateway: 10.0.29.1
        azs: [z1, z2, z3]
        dns: [168.63.129.16, 8.8.8.8]
        reserved: [10.0.29.0/30]
        cloud_properties:
          security_group: ((default_security_group))
          virtual_network_name: ((vnet_name))
          subnet_name: subnet-29
