#!/bin/bash -xeu

source e2e/functions/utils.sh
scenario=$1
scenario_path=$2

bosh -n -d $scenario deploy e2e/manifests/deployment.yml \
  -o ${scenario_path}/ops.yml \
  -v scenario=${scenario}


rg_name=$(get_rg_name ${scenario})
vm_name=$(get_vm_name ${scenario})

nics=$(az vm nic list --resource-group ${rg_name} --vm-name ${vm_name} | jq -r '. | length')

bosh -n -d $scenario delete-deployment

if [ "${nics}" == 2 ]
then
  echo "The number of nic is correct"
else
  echo "The number of nic is NOT correct"
  exit 1
fi
