#!/bin/bash -xeu

source e2e/functions/utils.sh
scenario=$1
scenario_path=$2

bosh -n -d $scenario deploy e2e/manifests/deployment.yml \
  -o ${scenario_path}/ops.yml \
  -v scenario=$scenario

rg_name=$(get_rg_name ${scenario})
vm_name=$(get_vm_name ${scenario})
nic_name="${vm_name}-0"

ip_forwarding=$(az network nic show --name ${nic_name} --resource-group ${rg_name} | jq -r '.enableIpForwarding')

bosh -n -d $scenario delete-deployment

if [ "${ip_forwarding}" == "true" ]
then
  echo "The ip forwarding is enabled successfully"
else
  exit 1
fi
