#!/bin/bash -xeu

source e2e/functions/utils.sh
scenario=$1
scenario_path=$2

bosh -n -d $scenario deploy e2e/manifests/deployment.yml \
  -o ${scenario_path}/ops.yml \
  -v scenario=$scenario

rg_name=$(get_rg_name ${scenario})
vm_name=$(get_vm_name ${scenario})

ip_allocation_method=$(az network public-ip show --name ${vm_name} --resource-group ${rg_name} | jq -r '.publicIpAllocationMethod')

bosh -n -d $scenario delete-deployment

if [ "${ip_allocation_method}" == "Dynamic" ]
then
  echo "The public ip allocation method is Dynamic"
else
  echo "The public ip allocation method is NOT Dynamic"
  exit 1
fi
