---
- type: replace
  path: /networks/-
  value:
    name: separate-public-ip
    type: manual
    subnets:
    - range: 10.0.27.0/24
      gateway: 10.0.27.1
      azs: [z1, z2, z3]
      dns: [168.63.129.16, 8.8.8.8]
      reserved: [10.0.27.0/30]
      cloud_properties:
        security_group: ((default_security_group))
        virtual_network_name: ((vnet_name))
        subnet_name: subnet-27
- type: replace
  path: /networks/-
  value:
    name: vip
    type: vip
    cloud_properties:
      resource_group_name: ((public_ip_resource_group_name))
