#!/bin/bash -xeu

source e2e/functions/utils.sh
scenario=$1
scenario_path=$2

bosh -n -d $scenario deploy e2e/manifests/deployment.yml \
  -o ${scenario_path}/ops.yml \
  -v scenario=$scenario

rg_name=$(get_rg_name ${scenario})
vm_name=$(get_vm_name ${scenario})

zone_number=$(az vm show --resource-group ${rg_name} --name ${vm_name} | jq -r '.zones[0]')

bosh -n -d $scenario delete-deployment

if [[ "${zone_number}" == "1" ]]
then
  echo "The availability zone is configured as expected"
else
  echo "The availability zone is NOT configured as expected"
  exit 1
fi
