#!/bin/bash -xeu

source e2e/functions/utils.sh
scenario=$1
scenario_path=$2

bosh -n -d $scenario deploy e2e/manifests/deployment.yml \
  -o ${scenario_path}/ops.yml \
  -v scenario=$scenario

nsg_name=$(cat environment/metadata | jq -r '.test_security_group')

rg_name=$(get_rg_name ${scenario})
vm_name=$(get_vm_name ${scenario})
nic_name="${vm_name}-0"
nic_id=$(az network nsg show --resource-group ${rg_name} --name ${nsg_name} | jq -r '.networkInterfaces[0].id')

bosh -n -d $scenario delete-deployment

if [[ "${nic_id}" =~ "${nic_name}" ]]
then
  echo "The network security is assigned to the specific nic successfully"
else
  echo "The network security is not assigned to the specific nic"
  exit 1
fi
