---
- type: replace
  path: /networks/-
  value:
    name: tags
    type: manual
    subnets:
    - range: 10.0.26.0/24
      gateway: 10.0.26.1
      azs: [z1, z2, z3]
      dns: [168.63.129.16, 8.8.8.8]
      reserved: [10.0.26.0/30]
      cloud_properties:
        security_group: ((default_security_group))
        virtual_network_name: ((vnet_name))
        subnet_name: subnet-26
- type: replace
  path: /vm_extensions/-
  value:
    name: tags
    cloud_properties:
      tags:
        test_name: test_value