#!/bin/bash -xeu

source e2e/functions/utils.sh
scenario=$1
scenario_path=$2

sku="standard"
bosh -n -d $scenario deploy e2e/manifests/deployment.yml \
  -o ${scenario_path}/ops.yml \
  -v scenario=$scenario \
  -v sku=$sku

bosh -n -d $scenario delete-deployment

rg_name=$(get_rg_name ${scenario})
vm_name=$(get_vm_name ${scenario})
backend_ipconf_id=$(az network lb list --resource-group ${rg_name} | jq -r '.[] | select(.name | contains("standard-lb")).backendAddressPools[0].backendIpConfigurations[0].id')

if [[ "${backend_ipconf_id}" =~ "${vm_name}" ]]
then
  echo "The standard load balancer is assigned to the specific nic successfully"
else
  echo "The standard load balancer is not assigned to the specific nic"
  exit 1
fi
