#!/bin/bash -xeu

source e2e/functions/utils.sh
scenario=$1
scenario_path=$2

bosh -n -d $scenario deploy e2e/manifests/deployment.yml \
  -o ${scenario_path}/ops.yml \
  -v scenario=$scenario

rg_name=$(get_rg_name ${scenario})
vm_name=$(get_vm_name ${scenario})

resources_id=$(az resource list | jq -r  --arg rg_name ${rg_name} '.[] | select(.resourceGroup == $rg_name).id')

bosh -n -d $scenario delete-deployment



if [[ "${rg_name}" == *"-temp" ]] \
&& [[ "${resources_id}" =~ "Microsoft.Compute/availabilitySets" ]] \
&& [[ "${resources_id}" =~ "Microsoft.Compute/virtualMachines" ]] \
&& [[ "${resources_id}" =~ "Microsoft.Network/networkInterfaces" ]] \
&& [[ "${resources_id}" =~ "Microsoft.Network/publicIPAddresses" ]] 
then
  az group delete --name ${rg_name} -y
  echo "All the resources are created in the expected resource group."
else
  exit 1
fi