#!/bin/bash -xeu

source e2e/functions/utils.sh
scenario=$1
scenario_path=$2

bosh -n -d $scenario deploy e2e/manifests/deployment.yml \
  -o ${scenario_path}/ops.yml \
  -v scenario=$scenario

rg_name=$(get_rg_name ${scenario})
vm_name=$(get_vm_name ${scenario})
nic_name="${vm_name}-0"

backend_pool=$(az network nic show --name ${nic_name} --resource-group ${rg_name} | jq -r '.ipConfigurations[0].applicationGatewayBackendAddressPools[0].id')

bosh -n -d $scenario delete-deployment

if [[ "${backend_pool}" =~ "default-agw" ]]
then
  echo "The application gateway is assigned to the specific nic successfully"
else
  echo "The application gateway is not assigned to the specific nic"
  exit 1
fi
