#!/bin/bash -xeu

source e2e/functions/utils.sh
scenario=$1
scenario_path=$2
director_vars_path=$(realpath pipelines/azure/assets/director-vars)

bosh -n -d $scenario deploy e2e/manifests/deployment.yml \
  -o ${scenario_path}/ops.yml \
  -v scenario=$scenario \
  -l <( ${director_vars_path} )

rg_name=$(get_rg_name ${scenario})
vm_name=$(get_vm_name ${scenario})
nic_name="${vm_name}-0"

public_ip_config=$(az network nic show --name ${nic_name} --resource-group ${rg_name} | jq -r '.ipConfigurations[].publicIpAddress')

bosh -n -d $scenario delete-deployment

if [[ "${public_ip_config}" == "null" ]]
then
  echo "The public ip is not configured as expected"
  exit 1
fi
