#!/bin/bash -xeu

source e2e/functions/utils.sh
scenario=$1
scenario_path=$2

bosh -n -d $scenario deploy ${scenario_path}/deployment.yml \
  -v scenario=$scenario

rg_name=$(get_rg_name ${scenario})

#Get size sku of instance nginx-1 and ephemeral disk size
vm_name_nginx_1=$(get_vm_name_by_instance_group ${scenario} "nginx-1")
vm_size_nginx_1=$(az vm show --resource-group ${rg_name} --name ${vm_name_nginx_1} | jq -r '.hardwareProfile.vmSize')
vm_cores_nginx_1=$(az vm list-sizes --location westeurope | jq -r --arg size ${vm_size_nginx_1} '.[] | select(.name == $size).numberOfCores')
vm_ram_nginx_1=$(az vm list-sizes --location westeurope | jq -r --arg size ${vm_size_nginx_1} '.[] | select(.name == $size).memoryInMb')

ephemeral_disk_size_nginx_1=$(az vm show --name ${vm_name_nginx_1} --resource-group ${rg_name} | jq -r '.storageProfile.dataDisks[] | select(.name | contains("ephemeral-disk")).diskSizeGb')

#Get size sku of instance nginx-2 and ephemeral disk size
vm_name_nginx_2=$(get_vm_name_by_instance_group ${scenario} "nginx-2")
vm_size_nginx_2=$(az vm show --resource-group ${rg_name} --name ${vm_name_nginx_2} | jq -r '.hardwareProfile.vmSize')
vm_cores_nginx_2=$(az vm list-sizes --location westeurope | jq -r --arg size ${vm_size_nginx_2} '.[] | select(.name == $size).numberOfCores')
vm_ram_nginx_2=$(az vm list-sizes --location westeurope | jq -r --arg size ${vm_size_nginx_2} '.[] | select(.name == $size).memoryInMb')

ephemeral_disk_size_nginx_2=$(az vm show --name ${vm_name_nginx_2} --resource-group ${rg_name} | jq -r '.storageProfile.dataDisks[] | select(.name | contains("ephemeral-disk")).diskSizeGb')

bosh -n -d $scenario delete-deployment

if [ ${ephemeral_disk_size_nginx_1} == 200 ] \
&& [ ${vm_cores_nginx_1} == 1 ] \
&& [ ${vm_ram_nginx_1} == 2048 ] \
&& [ ${ephemeral_disk_size_nginx_2} == 100 ] \
&& [ ${vm_cores_nginx_2} == 2 ] \
&& [ ${vm_ram_nginx_2} == 4096 ]
then
  echo "The vm size and ephemeral disk size is configured correctly"
else
  exit 1
fi
